language: julia

before_install:
- eval "$(ssh-agent -s)"
- echo -e $SSH_KEY |base64 -d >$HOME/.ssh/id_rsa
- chmod 600 $HOME/.ssh/id_rsa
- echo '|1|tCbF6ylipISewwuZfzDbsw623ic=|zj/fFRcWw7BfUrYvl0pTSmSfqNQ= ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBAGp1W0jQ217mdjE0OvggNr/wg9kHYYgmlTcA/ObLKN5bCtPpMJGDdm/vAYbSFaBtHHiOAQQmPg6LejJuOhk7Zo=' >>$HOME/.ssh/known_hosts
- echo '|1|jKCOWAH9yrDZ3ey2kQewgzuMjvc=|tivCVhqU7PCYU6Sz6AAAPN735/c= ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDypicw6GdbqBGMXgcrXoxRNUyOJWRBzv06a2TMlO7fQ34OSiekvBcJue7HLnFNYUpqlr7SHKynK8OcP8pFMntJEoDgIboWuFCphZhzEfBSjpryNF/Cp8jpF4vswi42FpbWCsooGn9NuXmW0isoCWQVEz73412gSvFnbgG/s8JSf21wlVl1yUDBI6m5btrikhGU34movU/3qQy44x/02pvBVAenTaSfH2IyjayUpr7vb0fF/inNCebmDAKitJ5vbfmVuoCYcZ0P+KSuR7XjVuFa2SbS5AJbUwKRj31tw4Fd1I1yii3XBKYm5DygkVCSIfTvu7Qi/B4nE97RymtSp5cr' >>$HOME/.ssh/known_hosts
- ssh-add $HOME/.ssh/id_rsa

env:
- PYTHON=""

julia:
- 1.0

cache:
  directories:
  - "$HOME/.julia"

script:
- export GKSwstype=100 && export GRDIR="" && julia --color=yes -e "using Pkg; Pkg.build(); Pkg.test(coverage=true)" && julia --color=yes docs/make.jl && julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'

deploy:
  skip_cleanup: true
  provider: script
  script: ".travis/deploy.sh"
  on:
    branch: master

notifications:
  slack:
    secure: QNldf8nSCPE4NQLyFEg5XZepu/dOK53bbPqCx6t/qs+TcT84Y7a8G74WoSZ+G7kmsQDhONB0BhcwL+Ct8VVp9PQnb4POYbZi4FwwKcfpwu9sXeWDp+epVQN1SuMHJLrmkr79SW/ZUdVHXIecAGZ1MofBuGCbM+TZIRJPgKQzxS7RLDpqxuzMYsN4ZEo8CLYz00toDKqoOhYq5o65b7HX1wB9iIJ9ufm++YQlcJS2F79WWVBCt/Me2KV6rCuyiUPSIaY87I9rhYshrFJlOsXa1yB1PJsNdkWfoAkg7oSQbHzGDVQazpH/OSmKCNLvRyJGqbmx9fGbXV6ZO5/rrKQAkoilWBS5KD4SQq6dGIGYUxgkWdhD/uFlOj5pN8Uno2z1BshfAyMKE5BcRzW96aws7JGWHlPeYfeU1gQAp5wlN5a9YIE6iB+H0ajiZC9OfGtvJtWah7qERdpKwe1AJoRd9hnr6VI5UdhiZl6zzYaNQ3E771D/bzy1TdU2ZFrJVD9CkkAQDLDwytWcy2uCYRpX7OI1WIdv59gFBqCkLMOcxRCXtA3YTNQmvp+5itrtKyX9ZBbBBWE1G/KH/0IrDX6uOl6GDTMYJnWcK1oy8WHSvM3EU8xz/QR+nPnO1ps2FD3vOEfnPSrNZ+mcmz/nhM4fc8hJOMJ0zcQsjcHaUAI9Gjk=
